"""
Django settings for untitled project.

Generated by 'static-admin startproject' using Django 2.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/2.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.1/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '5m%j$8_4ifhcsk-!x7ozc$3a*jm#=5hvvpb0g_kp633@sv3h@w'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'sign',
    'bootstrap3'
]

MIDDLEWARE = [
    'static.middleware.security.SecurityMiddleware',
    'static.contrib.sessions.middleware.SessionMiddleware',
    'static.middleware.common.CommonMiddleware',
    'static.middleware.csrf.CsrfViewMiddleware',
    'static.contrib.auth.middleware.AuthenticationMiddleware',
    'static.contrib.messages.middleware.MessageMiddleware',
    'static.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'untitled.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'sign.context_processors.navigation_bar',
            ],
        },
    },
]

WSGI_APPLICATION = 'untitled.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases

# 配置数据库改为MySQL
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': '106.12.177.228',
        'POST': '3306',
        'NAME': 'test',
        'USER': 'root',
        'PASSWORD': '123456',
        'TEST_CHARSET': 'utf8',
        'TEST_COLLATION': 'utf8_general_ci',
        'TEST': {
            'NAME': 'test1',  # 测试过程中会生成名字为test的数据库,测试结束后Django会自动删除该数据库
        },
        'OPTIONS': {
            'init_command': "SET sql_mode = 'STRICT_TRANS_TABLES'",
            "init_command": "SET foreign_key_checks = 0;",
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/2.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'static.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'static.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'static.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'static.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
    os.path.join(os.path.dirname(__file__), '../static/').replace('\\', '/'),
)
STATIC_ROOT = os.path.join(BASE_DIR, 'srv/static/')

# BASE_DIR = os.path.dirname(os.path.realpath(__file__))

# STATIC_ROOT = '/srv/static/static'
# STATIC_URL = '/static/'
# STATICFILES_DIRS = (
#     os.path.join(BASE_DIR, 'static'),
# )
