# Generated by Django 2.1.7 on 2019-08-27 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='page_base_mysql',
            new_name='base_mysql',
        ),
    ]
