# Generated by Django 2.1.7 on 2019-08-27 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20190827_0328'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='base_mysql',
            new_name='mysql_page',
        ),
    ]
