# Generated by Django 2.1.7 on 2019-07-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0002_auto_20190711_0834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='db_assert',
            name='test_case',
        ),
        migrations.RemoveField(
            model_name='precondition',
            name='test_case',
        ),
        migrations.DeleteModel(
            name='db_assert',
        ),
        migrations.DeleteModel(
            name='Precondition',
        ),
        migrations.DeleteModel(
            name='test_case',
        ),
    ]
