# Generated by Django 2.1.7 on 2019-07-11 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_auto_20190711_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='db_assert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assert_input', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('select_assert', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('assert_type', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('assert_input1', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Precondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_status', models.CharField(blank=True, default=None, max_length=5, null=True)),
                ('mobile', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('password', models.CharField(blank=True, default=None, max_length=6, null=True)),
                ('project_url', models.CharField(max_length=100)),
                ('select_port', models.CharField(max_length=20)),
                ('port_url', models.CharField(max_length=50)),
                ('key', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='test_case',
            fields=[
                ('id', models.CharField(max_length=35, primary_key=True, serialize=False)),
                ('test_case_name', models.CharField(max_length=15)),
                ('login_status', models.CharField(max_length=5)),
                ('mobile', models.CharField(max_length=11)),
                ('password', models.CharField(max_length=6)),
                ('project_id', models.CharField(max_length=100)),
                ('select_port', models.CharField(max_length=20)),
                ('port_url', models.CharField(max_length=50)),
                ('key', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('value', models.CharField(blank=True, default=None, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='precondition',
            name='test_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sign.test_case'),
        ),
        migrations.AddField(
            model_name='db_assert',
            name='test_case',
            field=models.ForeignKey(max_length=36, on_delete=django.db.models.deletion.CASCADE, to='sign.test_case'),
        ),
    ]
