# Generated by Django 2.1.7 on 2019-07-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0004_auto_20190711_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_assert',
            name='count',
            field=models.IntegerField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
